---
title: "Exam 1"
execute: 
  warning: false
  code: true
  number-sections: false
---




```{r}
library(tidytuesdayR)
library(tidyverse)
```


```{r}
#4.get data
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
```

```{r}
dim(fc)
names(fc)
head(fc)
```


```{r}
ggplot(fc, aes(x = consumption)) +
  geom_histogram(binwidth = 10, fill = "blue", color = "black") +
  labs(title = "Distribution of Food Consumption",
       x = "Consumption (kg/person/year)",
       y = "Frequency")
```

```{r}
# Bar plot for food_category
ggplot(fc, aes(x = food_category)) +
  geom_bar(fill = "blue", color = "black") +
  labs(title = "Distribution of Food Categories",
       x = "Food Category",
       y = "Count") 
```

```{r}
ggplot(fc, aes(x = country)) +
  geom_bar(fill = "skyblue", color = "black") +
  labs(title = "Distribution of Countries",
       x = "Country",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}
# Box plot of consumption by food category
ggplot(fc, aes(x = food_category, y = consumption, fill = food_category)) +
  geom_boxplot() +
  labs(title = "Food Consumption by Category",
       x = "Food Category",
       y = "Consumption (kg/person/year)") 
```

```{r}
ggplot(fc, aes(x = country, y = consumption, fill = country)) +
  geom_boxplot() +
  labs(title = "Food Consumption by Country",
       x = "Country",
       y = "Consumption (kg/person/year)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
ggplot(fc, aes(x = country, y = consumption, fill = food_category)) +
  geom_bar(stat = "identity", position = "dodge") +  
  labs(title = "Food Consumption by Country and Category",
       x = "Country",
       y = "Consumption (kg/person/year)",
       fill = "Food Category") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 10),  
        legend.position = "bottom") +  
  scale_fill_viridis_d()  

```
